---
Name: defaultpipeline
---
Pipeline:
  default_config:
    PipelineConfig:
      FilteredCommits: "DNFinishedCommits"
      Messages:
        Success: 'Deployment for <project>/<environment> has successfully completed'
        Failure: 'Deployment for <project>/<environment> has failed. See <pipelinelink>'
        Abort: 'Deployment for <project>/<environment> has been aborted'
        RollbackStarted: 'Deployment failed, rollback for <project>/<environment> has begun.'
        RollbackSuccess: 'Rollback for <project>/<environment> has successfully completed.'
        RollbackFailure: 'Rollback for <project>/<environment> has failed.'
      Subjects:
        Success: 'Deployment for <project>/<environment>: Success'
        Failure: 'Deployment for <project>/<environment>: Failure'
        Abort: 'Deployment for <project>/<environment>: Aborted'
        RollbackStarted: 'Deployment failed, rollback for <project>/<environment> has begun.'
        RollbackSuccess: 'Rollback for <project>/<environment> has successfully completed.'
        RollbackFailure: 'Rollback for <project>/<environment> has failed.'
    RollbackStep1:
      Class: RollbackStep
      RestoreDB: true
      MaxDuration: 3600
    RollbackStep2:
      Class: SmokeTestPipelineStep
      MaxDuration: 3600
---
Name: defaultconfirmationstep
---
UserConfirmationStep:
  default_config:
    MaxDuration: 604800 # Auto time out after a week
    Permissions:
      - APPROVE_DEPLOYMENT
    Messages:
      # Messages sent to all users (including <requester>)
      Cancel: 'Deployment for <project>/<environment> has been cancelled'
      TimeOut: 'Deployment approval for <project>/<environment> has timed out due to no response'
      # Messages only sent to requester
      Approve-Requester: 'Deployment for <project>/<environment> has been approved'
      Reject-Requester: 'Deployment for <project>/<environment> has been rejected'
      Request-Requester: 'You requested approval for deployment of <project>/<environment>. Cancel? <abortlink>'
      # Messages only sent to specified recipients
      Request-Recipient: 'Deployment for <project>/<environment> requested by <requester>. Login to approve at <approvelink>'
    Subjects:
      # Subject line for all users
      Cancel: 'Deployment for <project>/<environment>: Cancelled'
      TimeOut: 'Deployment for <project>/<environment>: Timeout'
      Request: 'Deployment for <project>/<environment>: Requested'
      # Messages only sent to requester
      Approve-Requester: 'Deployment for <project>/<environment>: Approved'
      Reject-Requester: 'Deployment for <project>/<environment>: Rejected'
---
Name: triggerdeploystep
---
TriggerDeployStep:
  default_config:
    MaxDuration: 604800 # Auto time out after a week
