---
Name: mysiteroutes
After: 'rootroutes'
---
Director:
  rules:
    '': '->naut'
    'naut/api//$Project/$Environment/$OtherID': 'DeploynautAPI'
    'naut': 'DNRoot'
    'graphite': 'GraphiteProxy'
